name: BuildPlugin
version: '${project.version}'
main: net.tenet.buildplugin.BuildPlugin
api-version: 1.19
authors: [Tenet]
depend: [WorldEdit]
commands:
  export_selection:
    description: Export selection